name: release

on:
  push:
    tags:
      - "v*"
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: ">=1.20.0"
          check-latest: true

      - uses: nolar/setup-k3d-k3s@v1
        with:
          skip-creation: true
          skip-readiness: true

      - name: Get Version
        id: get_version
        run: echo "VERSION=${GITHUB_REF##*/}" >> "${GITHUB_OUTPUT}"

      - name: Tests
        run: ./test/run all

      - name: Run Goreleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --config=.goreleaser.yaml --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ steps.get_version.outputs.VERSION }}
